import type { ReactNode } from 'react'

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <div style={{ marginBottom: '2rem' }}>
      <div style={{
        fontSize: '0.72rem', letterSpacing: '0.2em', color: 'var(--text-3)',
        textTransform: 'uppercase', marginBottom: '0.75rem',
      }}>
        {title}
      </div>
      <div style={{ fontSize: '0.95rem', color: 'var(--text-2)', lineHeight: 1.85 }}>
        {children}
      </div>
    </div>
  )
}

export default function TermsOfService() {
  return (
    <div style={{ minHeight: '100svh', background: 'var(--bg)', padding: '3rem 1.5rem 4rem' }}>
      <div style={{ maxWidth: '680px', margin: '0 auto' }}>

        {/* Header */}
        <div style={{ textAlign: 'center', marginBottom: '2.5rem' }}>
          <div
            className="font-jp"
            style={{ fontSize: '3.5rem', color: 'var(--red)', lineHeight: 1, marginBottom: '0.6rem', animation: 'kanjiPulse 4s ease-in-out infinite' }}
          >
            侍
          </div>
          <div style={{ fontSize: '1rem', letterSpacing: '0.44em', color: 'var(--text)', fontWeight: 500, textTransform: 'uppercase', marginBottom: '1.25rem' }}>
            Ronin Daily
          </div>
          <div style={{ height: '1px', background: 'var(--red)', opacity: 0.35, marginBottom: '1.75rem' }} />
          <div style={{ fontSize: '0.72rem', letterSpacing: '0.28em', color: 'var(--text-3)', textTransform: 'uppercase', marginBottom: '0.4rem' }}>
            Terms of Service
          </div>
          <div style={{ fontSize: '0.8rem', color: 'var(--text-3)' }}>
            Last updated: June 14, 2026
          </div>
        </div>

        <div style={{ height: '1px', background: 'var(--border)', marginBottom: '2.5rem' }} />

        <Section title="Not Medical Advice">
          Ronin Daily is a fitness tracking tool, not a medical service. Nothing in this app constitutes medical advice, diagnosis, or treatment. The calorie targets, movement goals, and meal plans generated by the app are informational tools only.
        </Section>

        <Section title="Consult a Doctor">
          Before starting any diet or exercise program, consult a qualified healthcare professional. This is especially important if you have any existing medical conditions, are pregnant, or have concerns about your health.
        </Section>

        <Section title="Your Responsibility">
          You are solely responsible for your own health and safety while using Ronin Daily. By using the app you acknowledge that you are voluntarily participating in a fitness program and assume all risk associated with it.
        </Section>

        <Section title="How Targets Are Calculated">
          Daily calorie and movement targets are calculated using the Mifflin-St Jeor equation, a widely accepted formula for estimating metabolic rate. These are estimates based on population averages. Individual results vary based on genetics, metabolism, adherence, and other factors. The app does not guarantee any specific outcome.
        </Section>

        <Section title="Limitation of Liability">
          Ronin Daily and its creators are not liable for any health outcomes, injuries, or adverse effects resulting from the use of this app or the fitness plans it generates. Use the app at your own risk.
        </Section>

        <Section title="Eligibility">
          You must be 18 years of age or older to use Ronin Daily. By creating an account you confirm that you meet this requirement.
        </Section>

        <Section title="Changes to the Service">
          We reserve the right to modify, suspend, or discontinue Ronin Daily at any time, with or without notice. We also reserve the right to update these terms. Continued use of the app after changes are posted constitutes your acceptance of the updated terms.
        </Section>

        <Section title="Contact">
          Questions about these terms? Email us at{' '}
          <span style={{ color: 'var(--text)' }}>support@ronindaily.app</span>.
        </Section>

        <div style={{ height: '1px', background: 'var(--border)', margin: '2rem 0' }} />

        <button
          onClick={() => { window.location.href = '/' }}
          style={{
            background: 'none', border: 'none', cursor: 'pointer', padding: 0,
            fontSize: '0.85rem', color: 'var(--text-3)', letterSpacing: '0.04em',
            transition: 'color 0.15s ease',
          }}
          onMouseEnter={(e) => { (e.target as HTMLButtonElement).style.color = 'var(--text)' }}
          onMouseLeave={(e) => { (e.target as HTMLButtonElement).style.color = 'var(--text-3)' }}
        >
          ← Back to Ronin Daily
        </button>

      </div>
    </div>
  )
}
